### ISSUE TITLE
Log size is restricted to less than 10MB only and rotated at local time.

### ISSUE THREAD

**Issue by longhavuong** [openziti/ziti-tunnel-apple#107]
I have a Mac Ziti Desktop version 2.22 installed in the Mac Mini M1 that has firmware version 12.4. I notice the service log (appex.log) is rotated before it reaches 10MB. Also the application log (app.log) is rotated at local time instead of UTC time like the Windows Ziti Desktop and Linux Ziti Tunneller as you can see below

       interns@HamAdlMacMini logs % date
       Fri Jul  8 23:09:19 ACST 2022

       interns@HamAdlMacMini logs % ls -lh
       total 33216
       -rw-r--r--@ 1 interns  staff   2.6K Jul  8 17:54 app.log
       -rw-r--r--@ 1 interns  staff   3.7K Jul  8 00:00 app.log.1
       -rw-r--r--@ 1 interns  staff    10K Jul  7 00:00 app.log.2
       -rw-r--r--@ 1 interns  staff   139K Jul  8 23:09 appex.log
       -rw-r--r--@ 1 interns  staff   7.3M Jul  8 23:09 appex.log.1
       -rw-r--r--@ 1 interns  staff   7.4M Jul  8 22:54 appex.log.2

I would request for a way to adjust the size limit of the log and to set the rotation to everyday at midnight UTC time to make it consistent with other platform.

**Comment by smilindave26** [comment]
We'll add something like this to macOS ZDE and include it in the next release (should be 2.23):

<img width="378" alt="image" src="https://user-images.githubusercontent.com/19175177/178317826-7e3d5661-e968-414a-8696-a2e4c937e2ea.png">

Default for macOS:
* rotateDaily: true 
* count: 5
* sizeMB: 50

Default for iOS:
* rotateDaily: true
* count: 2
* sizeMB: 5

**Comment by smilindave26** [comment]
Released to app store https://apps.apple.com/app/id1460484572
