### ISSUE TITLE
ease enrollment confusion

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti-tunnel-apple#167]
Adding an identity is confusing. New users can often not connect to services if given only a link to ZME in the App Store and a JWT. They need all of these instructions, and so eliminating some steps will help:

1. download the JWT file to your iPhone
2. install the ZME app
3. open the ZME app
4. push the add identity button
5. push the enroll this identity button
6. turn on the new identity
7. turn on the ZME tunnel
8. visit the Ziti service address

Steps 5-7 should happen immediately when a valid JWT is loaded.

A potential further enhancement would be registering some filename suffix (default app for filetype) like *.ziti or *.jwt (possible competition for this suffix) so that the ZME app can be auto-launched and enrollment triggered after only a confirmation prompt.

**Comment by smilindave26** [comment]
`.jwt`, `.zott`, and `.ziti` are already registered in the mobile app used by the included MobileShare extension. If you click on a file with one of these extensions, you can open the file with ZME (or any other app registered to open files with the extension). If you choose ZME you are shown a preview page showing the id, network name, expiration date, and option to Enroll or Cancel. A newly enrolled identity is automatically set to "Enabled" ('turned on')

The tunnel doesn't need to be turned on to enroll a new identity.  If it's already on, you are automatically directed to the identities page (that one that includes a list of services).  It would be simple to prompt the user if they want to connect the tunnel following enrollment (if it's not already connected)

Closing this issue. We can revisit UX updates (including an integrated 'getting started' flow) in the context of efforts around unified/next-gen UI currently progressing on other platforms.
