### ISSUE TITLE
Desktop/OSX 2.46 (524) - Disconnected after suspend/resume

### ISSUE THREAD

**Issue by marvkis** [openziti/ziti-tunnel-apple#195]
Hi @scareything,

I got the new build via testflight this morning - and had 2 times where OpenZITI did not reconnect / was not connected after resume.

Do you need logs? It seems to be quite reproducible ;)

Thanks & Bye,
    chris

**Comment by marvkis** [comment]
Hi Shawn,

I sent you a message via OpenZITI disclosure with the link as the logs are from my production environment ;)
The logs are collected after OpenZITI was disconnected after a resume. Just after waking up, OpenZITI's status icon was green for a short moment, then it turned grey and no tunnel was up.

I can't say exactly when the system went to sleep. It could have been about 20-30 minutes before the last timestamp.

**Comment by scareything** [comment]
Just so I'm clear, you're saying that the "Status" field in the Zit Desktop Edge UI (and menu bar pulldown) shows as "Disconnected" after waking from sleep? So you need to use the "Connect" button after waking Apparently not every time though?

**Comment by scareything** [comment]
I don't see any signs of trouble in the logs you sent. The PacketTunnelProvider process (appex.log) seems to simply stop. There are certainly no errors. I'm guessing this is a crash... Do you see any crash reports (in Console.app)?

**Comment by marvkis** [comment]
🤦 Sorry, I was in a hurry. Apple's crash reporter didn't show up, so I assumed there was nothing. But - there are crash reports. Will send you a chat message

**Comment by scareything** [comment]
Version 2.47 should take care of this. I'm not sure if you'll see it in the App Store or test flight first, but I sent it to both! Let me know if you see anything odd. Thanks again for the quick report and the helpful information!

**Comment by marvkis** [comment]
The 2.47 is stable again! Survived multiple sleep/wakeup sequences again! Thanks a lot!
